#ifndef _C_GL_BIND_SLOT_H_
#define _C_GL_BIND_SLOT_H_

#include "GL/glew.h"

#include <iostream>

enum CGLBindSlot 
{ 
	CGL_TEXTURE0_SLOT, CGL_TEXTURE1_SLOT, CGL_TEXTURE2_SLOT, CGL_TEXTURE3_SLOT,
	CGL_TEXTURE4_SLOT, CGL_TEXTURE5_SLOT, CGL_TEXTURE6_SLOT, CGL_TEXTURE7_SLOT, 
	CGL_TEXTURE8_SLOT, CGL_TEXTURE9_SLOT, CGL_TEXTURE10_SLOT, 
	CGL_FRAMEBUFFER_SLOT, CGL_RENDERBUFFER_SLOT,
	CGL_VERTEX_ARRAY_SLOT, CGL_UNIFORM_BUFFER_SLOT, CGL_PROGRAM_SLOT, CGL_ARRAY_BUFFER_SLOT,
	CGL_ELEMENT_ARRAY_BUFFER_SLOT
};

static GLenum GetGLSlot(CGLBindSlot slot) 
{
	switch(slot)
	{
	case CGL_TEXTURE0_SLOT: return GL_TEXTURE0;
	case CGL_TEXTURE1_SLOT: return GL_TEXTURE1;
	case CGL_TEXTURE2_SLOT: return GL_TEXTURE2;
	case CGL_TEXTURE3_SLOT: return GL_TEXTURE3;
	case CGL_TEXTURE4_SLOT: return GL_TEXTURE4;
	case CGL_TEXTURE5_SLOT: return GL_TEXTURE5;
	case CGL_TEXTURE6_SLOT: return GL_TEXTURE6;
	case CGL_TEXTURE7_SLOT: return GL_TEXTURE7;
	case CGL_TEXTURE8_SLOT: return GL_TEXTURE8;
	case CGL_TEXTURE9_SLOT: return GL_TEXTURE9;
	case CGL_TEXTURE10_SLOT: return GL_TEXTURE10;

	case CGL_FRAMEBUFFER_SLOT: return GL_FRAMEBUFFER;
	case CGL_RENDERBUFFER_SLOT: return GL_RENDERBUFFER;
	case CGL_VERTEX_ARRAY_SLOT: return GL_VERTEX_ARRAY;
	case CGL_UNIFORM_BUFFER_SLOT: return GL_UNIFORM_BUFFER;
	case CGL_ARRAY_BUFFER_SLOT: return GL_ARRAY_BUFFER;
	case CGL_ELEMENT_ARRAY_BUFFER_SLOT: return GL_ELEMENT_ARRAY_BUFFER;

	default: std::cout << "Invalid bind slot" << std::endl; return 0;
	}
}

#endif _C_GL_BIND_SLOT_H_